global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using FoundationKit.Domain.Enums;
global using FoundationKit.Domain.Dtos.Paginations;
global using Microsoft.AspNetCore.Mvc;
global using Foundationkit.Extensions.Encryptions.TNCI.Asymmetric;
global using Microsoft.EntityFrameworkCore;
global using System.Security.Cryptography;
global using System.Text;